syntax error nr.2

diff --git a/installer/bootstrap b/installer/bootstrap
--- a/installer/bootstrap
+++ b/installer/bootstrap
@@ -5,8 +5,6 @@ set -uo pipefail
 umask 077
 TTY="/dev/$(ps -p $$ -o tty=)"
 
-# Default install directory
-install_dir="/minecraft/paper-minecraft-vane"
 
 ################################################################
 # Helper functions
@@ -83,28 +81,28 @@ ask "Do you agree to the EULA?" \
 
 if ! getent passwd minecraft &>/dev/null; then
 	status "Creating minecraft user"
-	useradd --system --home-dir "$install_dir" --no-create-home minecraft \
+	useradd --system --home-dir /minecraft/paper-minecraft-vane --no-create-home minecraft \
 		|| die "Could not create user 'minecraft'"
 fi
 
-mkdir -p "$install_dir"
-chmod 700 "$install_dir"
-chown minecraft: "$install_dir"
+mkdir -p /minecraft/paper-minecraft-vane
+chmod 700 /minecraft/paper-minecraft-vane
+chown minecraft: /minecraft/paper-minecraft-vane
 
 
 ################################################################
 # Setup repository
 
-if [[ -e "$install_dir/deploy" ]]; then
-	echo "[33mThe deploy directory $install_dir/deploy already exists."
+if [[ -e /minecraft/paper-minecraft-vane/deploy ]]; then
+	echo "[33mThe deploy directory /minecraft/paper-minecraft-vane/deploy already exists."
 	echo "You can still run the installer again, but it may overwrite some"
 	echo "configuration files if you edited them in the meantime.[m"
 	ask "Are you sure you want to continue?" \
 		|| die "Installation aborted."
 fi
 
-cd "$install_dir" \
-	|| die "Could not change into $install_dir"
+cd /minecraft/paper-minecraft-vane \
+	|| die "Could not change into /minecraft/paper-minecraft-vane"
 
 chmod +x update.sh \
 	|| die "Could not make update.sh executable"
